# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Firmware
PRODUCT_COPY_FILES += \
    vendor/oppo/A37/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/oppo/A37/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/oppo/A37/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/oppo/A37/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/oppo/A37/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/oppo/A37/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/oppo/A37/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/oppo/A37/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/oppo/A37/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    vendor/oppo/A37/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/oppo/A37/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/oppo/A37/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/oppo/A37/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/oppo/A37/proprietary/etc/firmware/ice40.bin:system/etc/firmware/ice40.bin \
    vendor/oppo/A37/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/oppo/A37/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/oppo/A37/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/oppo/A37/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/oppo/A37/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/oppo/A37/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/oppo/A37/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/oppo/A37/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/oppo/A37/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/oppo/A37/proprietary/etc/firmware/widevine.b00:system/etc/firmware/widevine.b00 \
    vendor/oppo/A37/proprietary/etc/firmware/widevine.b01:system/etc/firmware/widevine.b01 \
    vendor/oppo/A37/proprietary/etc/firmware/widevine.b02:system/etc/firmware/widevine.b02 \
    vendor/oppo/A37/proprietary/etc/firmware/widevine.b03:system/etc/firmware/widevine.b03 \
    vendor/oppo/A37/proprietary/etc/firmware/widevine.mdt:system/etc/firmware/widevine.mdt \
    vendor/oppo/A37/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
    vendor/oppo/A37/proprietary/etc/firmware/wlan/prima/WCNSS_wlan_dictionary.dat:system/etc/firmware/wlan/prima/WCNSS_wlan_dictionary.dat

# Blobs
PRODUCT_COPY_FILES += \
    vendor/oppo/A37/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/oppo/A37/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/oppo/A37/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/oppo/A37/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/oppo/A37/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/oppo/A37/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/oppo/A37/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/oppo/A37/proprietary/etc/data/dsi_config.xml:system/vendor/etc/data/dsi_config.xml \
    vendor/oppo/A37/proprietary/etc/data/netmgr_config.xml:system/vendor/etc/data/netmgr_config.xml \
    vendor/oppo/A37/proprietary/etc/data/qmi_config.xml:system/vendor/etc/data/qmi_config.xml \
    vendor/oppo/A37/proprietary/etc/xtwifi.conf:system/etc/xtwifi.conf \
    vendor/oppo/A37/proprietary/lib/hw/camera.vendor.msm8916.so:system/lib/hw/camera.vendor.msm8916.so \
    vendor/oppo/A37/proprietary/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
    vendor/oppo/A37/proprietary/lib/hw/keystore.qcom.so:system/lib/hw/keystore.qcom.so \
    vendor/oppo/A37/proprietary/lib/hw/sensors.msm8916.so:system/lib/hw/sensors.msm8916.so \
    vendor/oppo/A37/proprietary/lib/libarcsoft_beautyshot.so:system/lib/libarcsoft_beautyshot.so \
    vendor/oppo/A37/proprietary/lib/libarcsoft_face_detection.so:system/lib/libarcsoft_face_detection.so \
    vendor/oppo/A37/proprietary/lib/libarcsoft_face_tracking.so:system/lib/libarcsoft_face_tracking.so \
    vendor/oppo/A37/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
    vendor/oppo/A37/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/oppo/A37/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/oppo/A37/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/oppo/A37/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/oppo/A37/proprietary/lib/libmpbase.so:system/lib/libmpbase.so \
    vendor/oppo/A37/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/oppo/A37/proprietary/lib/vendor.qti.hardware.fm@1.0.so:system/lib/vendor.qti.hardware.fm@1.0.so \
    vendor/oppo/A37/proprietary/lib64/hw/keystore.default.so:system/lib64/hw/keystore.default.so \
    vendor/oppo/A37/proprietary/lib64/hw/keystore.qcom.so:system/lib64/hw/keystore.qcom.so \
    vendor/oppo/A37/proprietary/lib64/hw/sensors.msm8916.so:system/lib64/hw/sensors.msm8916.so \
    vendor/oppo/A37/proprietary/lib64/libdivxdrmdecrypt.so:system/lib64/libdivxdrmdecrypt.so \
    vendor/oppo/A37/proprietary/lib64/libloc_api_v02.so:system/lib64/libloc_api_v02.so \
    vendor/oppo/A37/proprietary/lib64/libloc_ds_api.so:system/lib64/libloc_ds_api.so \
    vendor/oppo/A37/proprietary/lib64/vendor.qti.hardware.fm@1.0.so:system/lib64/vendor.qti.hardware.fm@1.0.so \
    vendor/oppo/A37/proprietary/vendor/bin/adsprpcd:system/vendor/bin/adsprpcd \
    vendor/oppo/A37/proprietary/vendor/bin/btnvtool:system/vendor/bin/btnvtool \
    vendor/oppo/A37/proprietary/vendor/bin/hci_qcomm_init:system/vendor/bin/hci_qcomm_init \
    vendor/oppo/A37/proprietary/vendor/bin/hw/android.hardware.drm@1.2-service.widevine:system/vendor/bin/hw/android.hardware.drm@1.2-service.widevine \
    vendor/oppo/A37/proprietary/vendor/bin/ims_rtp_daemon:system/vendor/bin/ims_rtp_daemon \
    vendor/oppo/A37/proprietary/vendor/bin/imscmservice:system/vendor/bin/imscmservice \
    vendor/oppo/A37/proprietary/vendor/bin/imsdatadaemon:system/vendor/bin/imsdatadaemon \
    vendor/oppo/A37/proprietary/vendor/bin/imsqmidaemon:system/vendor/bin/imsqmidaemon \
    vendor/oppo/A37/proprietary/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/oppo/A37/proprietary/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
    vendor/oppo/A37/proprietary/vendor/bin/move_widevine_data.sh:system/vendor/bin/move_widevine_data.sh \
    vendor/oppo/A37/proprietary/vendor/bin/msm_irqbalance:system/vendor/bin/msm_irqbalance \
    vendor/oppo/A37/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/oppo/A37/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/oppo/A37/proprietary/vendor/bin/qseecomd:system/vendor/bin/qseecomd \
    vendor/oppo/A37/proprietary/vendor/bin/radish:system/vendor/bin/radish \
    vendor/oppo/A37/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/oppo/A37/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/oppo/A37/proprietary/vendor/bin/time_daemon:system/vendor/bin/time_daemon \
    vendor/oppo/A37/proprietary/vendor/bin/vm_bms:system/vendor/bin/vm_bms \
    vendor/oppo/A37/proprietary/vendor/etc/calmodule.cfg:system/vendor/etc/calmodule.cfg \
    vendor/oppo/A37/proprietary/vendor/etc/init/android.hardware.drm@1.2-service.widevine.rc:system/vendor/etc/init/android.hardware.drm@1.2-service.widevine.rc \
    vendor/oppo/A37/proprietary/vendor/etc/msm_irqbalance.conf:system/vendor/etc/msm_irqbalance.conf \
    vendor/oppo/A37/proprietary/vendor/etc/permissions/imscm.xml:system/vendor/etc/permissions/imscm.xml \
    vendor/oppo/A37/proprietary/vendor/etc/permissions/qcnvitems.xml:system/vendor/etc/permissions/qcnvitems.xml \
    vendor/oppo/A37/proprietary/vendor/etc/permissions/qcrilhook.xml:system/vendor/etc/permissions/qcrilhook.xml \
    vendor/oppo/A37/proprietary/vendor/etc/permissions/qti_permissions.xml:system/vendor/etc/permissions/qti_permissions.xml \
    vendor/oppo/A37/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/oppo/A37/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/oppo/A37/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/oppo/A37/proprietary/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/oppo/A37/proprietary/vendor/lib/hw/sound_trigger.primary.msm8916.so:system/vendor/lib/hw/sound_trigger.primary.msm8916.so \
    vendor/oppo/A37/proprietary/vendor/lib/hw/vendor.qti.hardware.fm@1.0-impl.so:system/vendor/lib/hw/vendor.qti.hardware.fm@1.0-impl.so \
    vendor/oppo/A37/proprietary/vendor/lib/hw/wbc_hal.default.so:system/vendor/lib/hw/wbc_hal.default.so \
    vendor/oppo/A37/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/oppo/A37/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/oppo/A37/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/oppo/A37/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
    vendor/oppo/A37/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/oppo/A37/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOmxAlacDec.so:system/vendor/lib/libOmxAlacDec.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOmxAlacDecSw.so:system/vendor/lib/libOmxAlacDecSw.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOmxAmrDec.so:system/vendor/lib/libOmxAmrDec.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOmxApeDec.so:system/vendor/lib/libOmxApeDec.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOmxApeDecSw.so:system/vendor/lib/libOmxApeDecSw.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOmxVideoDSMode.so:system/vendor/lib/libOmxVideoDSMode.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOmxVpp.so:system/vendor/lib/libOmxVpp.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
    vendor/oppo/A37/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/oppo/A37/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/oppo/A37/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/oppo/A37/proprietary/vendor/lib/libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so \
    vendor/oppo/A37/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/oppo/A37/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/oppo/A37/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/oppo/A37/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    vendor/oppo/A37/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/oppo/A37/proprietary/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so \
    vendor/oppo/A37/proprietary/vendor/lib/libactuator_dw9714_camcorder.so:system/vendor/lib/libactuator_dw9714_camcorder.so \
    vendor/oppo/A37/proprietary/vendor/lib/libactuator_dw9714_camera.so:system/vendor/lib/libactuator_dw9714_camera.so \
    vendor/oppo/A37/proprietary/vendor/lib/libactuator_dw9714_15399.so:system/vendor/lib/libactuator_dw9714_15399.so \
    vendor/oppo/A37/proprietary/vendor/lib/libactuator_dw9714_15399_camcorder.so:system/vendor/lib/libactuator_dw9714_15399_camcorder.so \
    vendor/oppo/A37/proprietary/vendor/lib/libactuator_dw9714_15399_camera.so:system/vendor/lib/libactuator_dw9714_15399_camera.so \
    vendor/oppo/A37/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/oppo/A37/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/oppo/A37/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/oppo/A37/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/oppo/A37/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    vendor/oppo/A37/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/oppo/A37/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/oppo/A37/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/oppo/A37/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/oppo/A37/proprietary/vendor/lib/libcalmodule_akm.so:system/vendor/lib/libcalmodule_akm.so \
    vendor/oppo/A37/proprietary/vendor/lib/libcalmodule_common.so:system/vendor/lib/libcalmodule_common.so \
    vendor/oppo/A37/proprietary/vendor/lib/libcalmodule_gyroscope.so:system/vendor/lib/libcalmodule_gyroscope.so \
    vendor/oppo/A37/proprietary/vendor/lib/libcamerahandler_jni.so:system/vendor/lib/libcamerahandler_jni.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_hi545_15399_common.so:system/vendor/lib/libchromatix_hi545_15399_common.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_hi545_15399_default_video.so:system/vendor/lib/libchromatix_hi545_15399_default_video.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_hi545_15399_preview.so:system/vendor/lib/libchromatix_hi545_15399_preview.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_hi545_15399_snapshot.so:system/vendor/lib/libchromatix_hi545_15399_snapshot.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_common.so:system/vendor/lib/libchromatix_imx179_15399_common.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_common_new.so:system/vendor/lib/libchromatix_imx179_15399_common_new.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_default_video.so:system/vendor/lib/libchromatix_imx179_15399_default_video.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_hfr_120.so:system/vendor/lib/libchromatix_imx179_15399_hfr_120.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_liveshot.so:system/vendor/lib/libchromatix_imx179_15399_liveshot.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_preview.so:system/vendor/lib/libchromatix_imx179_15399_preview.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_preview_binning.so:system/vendor/lib/libchromatix_imx179_15399_preview_binning.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_preview_binning_new.so:system/vendor/lib/libchromatix_imx179_15399_preview_binning_new.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_preview_new.so:system/vendor/lib/libchromatix_imx179_15399_preview_new.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_preview_sunny.so:system/vendor/lib/libchromatix_imx179_15399_preview_sunny.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_preview_sunny_new.so:system/vendor/lib/libchromatix_imx179_15399_preview_sunny_new.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_snapshot.so:system/vendor/lib/libchromatix_imx179_15399_snapshot.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_video_binning.so:system/vendor/lib/libchromatix_imx179_15399_video_binning.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_imx179_15399_video_hd.so:system/vendor/lib/libchromatix_imx179_15399_video_hd.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_ov5648_15399_common.so:system/vendor/lib/libchromatix_ov5648_15399_common.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_ov5648_15399_default_video.so:system/vendor/lib/libchromatix_ov5648_15399_default_video.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_ov5648_15399_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_15399_default_video_hd.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_ov5648_15399_preview.so:system/vendor/lib/libchromatix_ov5648_15399_preview.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_ov5648_15399_preview_cmcc.so:system/vendor/lib/libchromatix_ov5648_15399_preview_cmcc.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_ov5648_15399_preview_fb.so:system/vendor/lib/libchromatix_ov5648_15399_preview_fb.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_ov5648_15399_small_video.so:system/vendor/lib/libchromatix_ov5648_15399_small_video.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_ov5648_15399_snapshot.so:system/vendor/lib/libchromatix_ov5648_15399_snapshot.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_ov5648_15399_snapshot_fb.so:system/vendor/lib/libchromatix_ov5648_15399_snapshot_fb.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_ov5648_15399_zsl.so:system/vendor/lib/libchromatix_ov5648_15399_zsl.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_common.so:system/vendor/lib/libchromatix_s5k3h7_15399_common.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_default_video.so:system/vendor/lib/libchromatix_s5k3h7_15399_default_video.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_default_video_otp.so:system/vendor/lib/libchromatix_s5k3h7_15399_default_video_otp.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_preview.so:system/vendor/lib/libchromatix_s5k3h7_15399_preview.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_preview_cmcc.so:system/vendor/lib/libchromatix_s5k3h7_15399_preview_cmcc.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_preview_new.so:system/vendor/lib/libchromatix_s5k3h7_15399_preview_new.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_preview_otp.so:system/vendor/lib/libchromatix_s5k3h7_15399_preview_otp.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_preview_otp_new.so:system/vendor/lib/libchromatix_s5k3h7_15399_preview_otp_new.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_small_video.so:system/vendor/lib/libchromatix_s5k3h7_15399_small_video.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_snapshot.so:system/vendor/lib/libchromatix_s5k3h7_15399_snapshot.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_snapshot_cmcc.so:system/vendor/lib/libchromatix_s5k3h7_15399_snapshot_cmcc.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_snapshot_otp.so:system/vendor/lib/libchromatix_s5k3h7_15399_snapshot_otp.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_15399_zsl_off.so:system/vendor/lib/libchromatix_s5k3h7_15399_zsl_off.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_8916_common.so:system/vendor/lib/libchromatix_s5k3h7_8916_common.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_8916_default_video.so:system/vendor/lib/libchromatix_s5k3h7_8916_default_video.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_8916_preview.so:system/vendor/lib/libchromatix_s5k3h7_8916_preview.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_8916_preview_cmcc.so:system/vendor/lib/libchromatix_s5k3h7_8916_preview_cmcc.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_8916_small_video.so:system/vendor/lib/libchromatix_s5k3h7_8916_small_video.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_8916_snapshot.so:system/vendor/lib/libchromatix_s5k3h7_8916_snapshot.so \
    vendor/oppo/A37/proprietary/vendor/lib/libchromatix_s5k3h7_8916_zsl_off.so:system/vendor/lib/libchromatix_s5k3h7_8916_zsl_off.so \
    vendor/oppo/A37/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/oppo/A37/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/oppo/A37/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/oppo/A37/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/oppo/A37/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/oppo/A37/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/oppo/A37/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/oppo/A37/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/oppo/A37/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/oppo/A37/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/oppo/A37/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/oppo/A37/proprietary/vendor/lib/libhwdaphal.so:system/vendor/lib/libhwdaphal.so \
    vendor/oppo/A37/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/oppo/A37/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/oppo/A37/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/oppo/A37/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/oppo/A37/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/oppo/A37/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/oppo/A37/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_hi545_15399.so:system/vendor/lib/libmmcamera_hi545_15399.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_hynix_hi545_eeprom.so:system/vendor/lib/libmmcamera_hynix_hi545_eeprom.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_imx179_15399.so:system/vendor/lib/libmmcamera_imx179_15399.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_omnivision_5648_eeprom.so:system/vendor/lib/libmmcamera_omnivision_5648_eeprom.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_ov5648_15399.so:system/vendor/lib/libmmcamera_ov5648_15399.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_s5k3h7_15399.so:system/vendor/lib/libmmcamera_s5k3h7_15399.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_s5k3h7_8916.so:system/vendor/lib/libmmcamera_s5k3h7_8916.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_sony_imx179_eeprom.so:system/vendor/lib/libmmcamera_sony_imx179_eeprom.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_truly_s5k3h7_eeprom.so:system/vendor/lib/libmmcamera_truly_s5k3h7_eeprom.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_truly_s5k3h7_new_eeprom.so:system/vendor/lib/libmmcamera_truly_s5k3h7_new_eeprom.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
    vendor/oppo/A37/proprietary/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
    vendor/oppo/A37/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/oppo/A37/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/oppo/A37/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqct_resampler.so:system/vendor/lib/libqct_resampler.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/oppo/A37/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/oppo/A37/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/oppo/A37/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/oppo/A37/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/oppo/A37/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/oppo/A37/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/oppo/A37/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/oppo/A37/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    vendor/oppo/A37/proprietary/vendor/lib/libscve_mv.so:system/vendor/lib/libscve_mv.so \
    vendor/oppo/A37/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/oppo/A37/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/oppo/A37/proprietary/vendor/lib/libstlport.so:system/vendor/lib/libstlport.so \
    vendor/oppo/A37/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
    vendor/oppo/A37/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/oppo/A37/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/oppo/A37/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/oppo/A37/proprietary/vendor/lib/libts_detected_face_hal.so:system/vendor/lib/libts_detected_face_hal.so \
    vendor/oppo/A37/proprietary/vendor/lib/libts_face_beautify_hal.so:system/vendor/lib/libts_face_beautify_hal.so \
    vendor/oppo/A37/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
    vendor/oppo/A37/proprietary/vendor/lib/libvoice-svc.so:system/vendor/lib/libvoice-svc.so \
    vendor/oppo/A37/proprietary/vendor/lib/libvpplibrary.so:system/vendor/lib/libvpplibrary.so \
    vendor/oppo/A37/proprietary/vendor/lib/libvqzip.so:system/vendor/lib/libvqzip.so \
    vendor/oppo/A37/proprietary/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so \
    vendor/oppo/A37/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/oppo/A37/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/oppo/A37/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/oppo/A37/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/oppo/A37/proprietary/vendor/lib/soundfx/libswdap.so:system/vendor/lib/soundfx/libswdap.so \
    vendor/oppo/A37/proprietary/vendor/lib/vendor.qti.hardware.fm@1.0_vendor.so:system/vendor/lib/vendor.qti.hardware.fm@1.0_vendor.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/eglsubAndroid.so:system/vendor/lib64/egl/eglsubAndroid.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/libESXEGL_adreno.so:system/vendor/lib64/egl/libESXEGL_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib64/egl/libESXGLESv1_CM_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/libESXGLESv2_adreno.so:system/vendor/lib64/egl/libESXGLESv2_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/libQTapGLES.so:system/vendor/lib64/egl/libQTapGLES.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/libRBEGL_adreno.so:system/vendor/lib64/egl/libRBEGL_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib64/egl/libRBGLESv1_CM_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/libRBGLESv2_adreno.so:system/vendor/lib64/egl/libRBGLESv2_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib64/hw/flp.default.so:system/vendor/lib64/hw/flp.default.so \
    vendor/oppo/A37/proprietary/vendor/lib64/hw/vendor.qti.hardware.fm@1.0-impl.so:system/vendor/lib64/hw/vendor.qti.hardware.fm@1.0-impl.so \
    vendor/oppo/A37/proprietary/vendor/lib64/hw/wbc_hal.default.so:system/vendor/lib64/hw/wbc_hal.default.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-dplmedia.so:system/vendor/lib64/lib-dplmedia.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-ims-rcscmjni.so:system/vendor/lib64/lib-ims-rcscmjni.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-imsSDP.so:system/vendor/lib64/lib-imsSDP.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-imscamera.so:system/vendor/lib64/lib-imscamera.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-imsdpl.so:system/vendor/lib64/lib-imsdpl.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-imsqimf.so:system/vendor/lib64/lib-imsqimf.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-imsrcs.so:system/vendor/lib64/lib-imsrcs.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-imsrcscm.so:system/vendor/lib64/lib-imsrcscm.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-imsrcscmclient.so:system/vendor/lib64/lib-imsrcscmclient.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-imsrcscmservice.so:system/vendor/lib64/lib-imsrcscmservice.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-imss.so:system/vendor/lib64/lib-imss.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-imsvt.so:system/vendor/lib64/lib-imsvt.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-imsxml.so:system/vendor/lib64/lib-imsxml.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-rcsimssjni.so:system/vendor/lib64/lib-rcsimssjni.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-rcsjni.so:system/vendor/lib64/lib-rcsjni.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-rtpcommon.so:system/vendor/lib64/lib-rtpcommon.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-rtpcore.so:system/vendor/lib64/lib-rtpcore.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-rtpdaemoninterface.so:system/vendor/lib64/lib-rtpdaemoninterface.so \
    vendor/oppo/A37/proprietary/vendor/lib64/lib-rtpsl.so:system/vendor/lib64/lib-rtpsl.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libDivxDrm.so:system/vendor/lib64/libDivxDrm.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libFileMux.so:system/vendor/lib64/libFileMux.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libFlacSwDec.so:system/vendor/lib64/libFlacSwDec.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libSHIMDivxDrm.so:system/vendor/lib64/libSHIMDivxDrm.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libSubSystemShutdown.so:system/vendor/lib64/libSubSystemShutdown.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libTimeService.so:system/vendor/lib64/libTimeService.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libacdbmapper.so:system/vendor/lib64/libacdbmapper.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libactuator_dw9714_15399.so:system/vendor/lib64/libactuator_dw9714_15399.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libactuator_dw9714_15399_camcorder.so:system/vendor/lib64/libactuator_dw9714_15399_camcorder.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libactuator_dw9714_15399_camera.so:system/vendor/lib64/libactuator_dw9714_15399_camera.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libaudioalsa.so:system/vendor/lib64/libaudioalsa.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libbccQTI.so:system/vendor/lib64/libbccQTI.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libbtnv.so:system/vendor/lib64/libbtnv.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libc2d30-a3xx.so:system/vendor/lib64/libc2d30-a3xx.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libcalmodule_akm.so:system/vendor/lib64/libcalmodule_akm.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libcalmodule_common.so:system/vendor/lib64/libcalmodule_common.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libcalmodule_gyroscope.so:system/vendor/lib64/libcalmodule_gyroscope.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libcalmodule_senodia.so:system/vendor/lib64/libcalmodule_senodia.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_hi545_15399_common.so:system/vendor/lib64/libchromatix_hi545_15399_common.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_hi545_15399_default_video.so:system/vendor/lib64/libchromatix_hi545_15399_default_video.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_hi545_15399_preview.so:system/vendor/lib64/libchromatix_hi545_15399_preview.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_hi545_15399_snapshot.so:system/vendor/lib64/libchromatix_hi545_15399_snapshot.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_common.so:system/vendor/lib64/libchromatix_imx179_15399_common.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_common_new.so:system/vendor/lib64/libchromatix_imx179_15399_common_new.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_default_video.so:system/vendor/lib64/libchromatix_imx179_15399_default_video.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_hfr_120.so:system/vendor/lib64/libchromatix_imx179_15399_hfr_120.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_liveshot.so:system/vendor/lib64/libchromatix_imx179_15399_liveshot.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_preview.so:system/vendor/lib64/libchromatix_imx179_15399_preview.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_preview_binning.so:system/vendor/lib64/libchromatix_imx179_15399_preview_binning.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_preview_binning_new.so:system/vendor/lib64/libchromatix_imx179_15399_preview_binning_new.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_preview_new.so:system/vendor/lib64/libchromatix_imx179_15399_preview_new.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_preview_sunny.so:system/vendor/lib64/libchromatix_imx179_15399_preview_sunny.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_preview_sunny_new.so:system/vendor/lib64/libchromatix_imx179_15399_preview_sunny_new.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_snapshot.so:system/vendor/lib64/libchromatix_imx179_15399_snapshot.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_video_binning.so:system/vendor/lib64/libchromatix_imx179_15399_video_binning.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_imx179_15399_video_hd.so:system/vendor/lib64/libchromatix_imx179_15399_video_hd.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_ov5648_15399_common.so:system/vendor/lib64/libchromatix_ov5648_15399_common.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_ov5648_15399_default_video.so:system/vendor/lib64/libchromatix_ov5648_15399_default_video.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_ov5648_15399_default_video_hd.so:system/vendor/lib64/libchromatix_ov5648_15399_default_video_hd.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_ov5648_15399_preview.so:system/vendor/lib64/libchromatix_ov5648_15399_preview.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_ov5648_15399_preview_fb.so:system/vendor/lib64/libchromatix_ov5648_15399_preview_fb.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_ov5648_15399_small_video.so:system/vendor/lib64/libchromatix_ov5648_15399_small_video.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_ov5648_15399_snapshot.so:system/vendor/lib64/libchromatix_ov5648_15399_snapshot.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_ov5648_15399_snapshot_fb.so:system/vendor/lib64/libchromatix_ov5648_15399_snapshot_fb.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_ov5648_15399_zsl.so:system/vendor/lib64/libchromatix_ov5648_15399_zsl.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_15399_common.so:system/vendor/lib64/libchromatix_s5k3h7_15399_common.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_15399_default_video.so:system/vendor/lib64/libchromatix_s5k3h7_15399_default_video.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_15399_default_video_otp.so:system/vendor/lib64/libchromatix_s5k3h7_15399_default_video_otp.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_15399_preview.so:system/vendor/lib64/libchromatix_s5k3h7_15399_preview.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_15399_preview_new.so:system/vendor/lib64/libchromatix_s5k3h7_15399_preview_new.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_15399_preview_otp.so:system/vendor/lib64/libchromatix_s5k3h7_15399_preview_otp.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_15399_preview_otp_new.so:system/vendor/lib64/libchromatix_s5k3h7_15399_preview_otp_new.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_15399_small_video.so:system/vendor/lib64/libchromatix_s5k3h7_15399_small_video.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_15399_snapshot.so:system/vendor/lib64/libchromatix_s5k3h7_15399_snapshot.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_15399_snapshot_cmcc.so:system/vendor/lib64/libchromatix_s5k3h7_15399_snapshot_cmcc.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_15399_snapshot_otp.so:system/vendor/lib64/libchromatix_s5k3h7_15399_snapshot_otp.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_15399_zsl_off.so:system/vendor/lib64/libchromatix_s5k3h7_15399_zsl_off.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_8916_common.so:system/vendor/lib64/libchromatix_s5k3h7_8916_common.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_8916_default_video.so:system/vendor/lib64/libchromatix_s5k3h7_8916_default_video.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_8916_preview.so:system/vendor/lib64/libchromatix_s5k3h7_8916_preview.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_8916_small_video.so:system/vendor/lib64/libchromatix_s5k3h7_8916_small_video.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_8916_snapshot.so:system/vendor/lib64/libchromatix_s5k3h7_8916_snapshot.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libchromatix_s5k3h7_8916_zsl_off.so:system/vendor/lib64/libchromatix_s5k3h7_8916_zsl_off.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libflp.so:system/vendor/lib64/libflp.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libhwdaphal.so:system/vendor/lib64/libhwdaphal.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libimscamera_jni.so:system/vendor/lib64/libimscamera_jni.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libimsmedia_jni.so:system/vendor/lib64/libimsmedia_jni.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so \
    vendor/oppo/A37/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
    vendor/oppo/A37/proprietary/vendor/lib64/liblqe.so:system/vendor/lib64/liblqe.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libmm-disp-apis.so:system/vendor/lib64/libmm-disp-apis.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libmm-hdcpmgr.so:system/vendor/lib64/libmm-hdcpmgr.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libmmcamera_hi545_15399.so:system/vendor/lib64/libmmcamera_hi545_15399.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libmmcamera_imx179_15399.so:system/vendor/lib64/libmmcamera_imx179_15399.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libmmcamera_ov5648_15399.so:system/vendor/lib64/libmmcamera_ov5648_15399.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libmmcamera_s5k3h7_15399.so:system/vendor/lib64/libmmcamera_s5k3h7_15399.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libmmcamera_s5k3h7_8916.so:system/vendor/lib64/libmmcamera_s5k3h7_8916.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libmmosal.so:system/vendor/lib64/libmmosal.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libmmrtpdecoder.so:system/vendor/lib64/libmmrtpdecoder.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libmmrtpencoder.so:system/vendor/lib64/libmmrtpencoder.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libril-qc-radioconfig.so:system/vendor/lib64/libril-qc-radioconfig.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/oppo/A37/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
    vendor/oppo/A37/proprietary/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so \
    vendor/oppo/A37/proprietary/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libsc-a3xx.so:system/vendor/lib64/libsc-a3xx.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libscale.so:system/vendor/lib64/libscale.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libsubsystem_control.so:system/vendor/lib64/libsubsystem_control.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libtime_genoff.so:system/vendor/lib64/libtime_genoff.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libtzdrmgenprov.so:system/vendor/lib64/libtzdrmgenprov.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libvcel.so:system/vendor/lib64/libvcel.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libvoice-svc.so:system/vendor/lib64/libvoice-svc.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libwfdcommonutils.so:system/vendor/lib64/libwfdcommonutils.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libwvhidl.so:system/vendor/lib64/libwvhidl.so \
    vendor/oppo/A37/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
    vendor/oppo/A37/proprietary/vendor/lib64/vendor.qti.hardware.fm@1.0_vendor.so:system/vendor/lib64/vendor.qti.hardware.fm@1.0_vendor.so

PRODUCT_PACKAGES += \
    colorservice \
    ims \
    imscmlibrary \
    imssettings \
    qcrilmsgtunnel \
    qcnvitems \
    qcrilhook \
    shutdownlistener \
    TimeService
